application: placesatdhs
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /css
  static_dir: css

- url: /pictures
  static_dir: pictures
  
- url: /.*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
